### ISSUE TITLE
Docs: Preview link (pointing to a Vercel app) does not work

### ISSUE THREAD

**Issue by rowild** [Boluwatife2904/movies-app#1]
Any new link available?

**Comment by Boluwatife2904** [comment]
Sorry about that, I have updated it. You can find preview it here - https://findamovie.vercel.app

**Comment by rowild** [comment]
Thank you for your quick response! :-) 
Nice app!

**Comment by Boluwatife2904** [comment]
No problem. Thanks for pointing that out as well. Thanks and enjoy the rest of your day.
